---
version: '3'

services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=django
            - MYSQL_USER=django
            - MYSQL_PASSWORD=django
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        healthcheck:
            test: "exit 0"
        
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy